Repository artsy/fresnel, pull requests merged in 2021-09, with the labels that each got.

#198 feature: Node 14 LTS
  .nvmrc
  examples/ssr-rendering/package.json
  examples/ssr-rendering/yarn.lock
  package.json
  yarn.lock
Labels: Version: Major

#199 Revert "feature: Node 14 LTS"
  .nvmrc
  examples/ssr-rendering/package.json
  examples/ssr-rendering/yarn.lock
  package.json
  yarn.lock
Labels: Version: Minor

#200 feature: Node 14 LTS
  .nvmrc
  examples/ssr-rendering/package.json
  examples/ssr-rendering/yarn.lock
  package.json
  yarn.lock
Labels: Version: Major

#201 chore: Dependabot Configuration
  .github/dependabot.yml
Labels: Version: Trivial

#207 chore: Security Updates
  package.json
  yarn.lock
Labels: Version: Patch
