Repository artsy/fresnel, pull requests merged in 2022-08, with the labels that each got.

#287 chore(lib): Upgrade to React 18
  README.md
  examples/basic/package.json
  examples/basic/src/client.tsx
  examples/basic/src/server.tsx
  examples/basic/yarn.lock
  examples/gatsby/.gitignore
  examples/gatsby/.prettierrc
  examples/gatsby/README.md
  examples/gatsby/gatsby-browser.js
  examples/gatsby/gatsby-config.js
  examples/gatsby/gatsby-ssr.js
  examples/gatsby/package.json
  examples/gatsby/src/Boot.tsx
  examples/gatsby/src/Media.tsx
  examples/gatsby/src/html.js
  examples/gatsby/src/pages/index.tsx
  examples/gatsby/yarn.lock
  examples/kitchen-sink/package.json
  examples/kitchen-sink/src/server.tsx
  examples/kitchen-sink/yarn.lock
  examples/nextjs/next-env.d.ts
  examples/nextjs/package.json
  examples/nextjs/src/pages/index.tsx
  examples/nextjs/tsconfig.json
  examples/nextjs/yarn.lock
  examples/ssr-rendering/package.json
  examples/ssr-rendering/src/App.tsx
  examples/ssr-rendering/src/client.tsx
  examples/ssr-rendering/src/server.tsx
  examples/ssr-rendering/yarn.lock
  package.json
  src/Breakpoints.ts
  src/Media.tsx
  src/__test__/Media.test.tsx
  tslint.json
  yarn.lock
Labels: Version: Major

#290 feat(react-18): Add official React 18 SSR support
  examples/nextjs/src/components/Articles.tsx
  examples/nextjs/src/components/Artists.tsx
  examples/nextjs/src/components/Desktop.tsx
  examples/nextjs/src/components/Mobile.tsx
  examples/nextjs/src/pages/index.tsx
  examples/nextjs/src/utils/api.ts
  examples/nextjs/src/utils/suspensePromise.ts
  examples/ssr-rendering/src/App.tsx
  package.json
  src/DynamicResponsive.tsx
  src/Media.tsx
  src/__test__/Media.test.tsx
  src/index.tsx
  src/suspense/Suspender.tsx
  src/suspense/SuspenseWrapper.tsx
  src/suspense/suspense.tsx
  yarn.lock
Labels: Version: Major

#291 docs(react-18): Update to remove unnecessary warning
  README.md
  package.json
Labels: Version: Patch

#293 Fix typo in `REAMDE.md`
  README.md
Labels: Version: Minor
