Repository artsy/fresnel, pull requests merged in 2022-02, with the labels that each got.

#248 Added memoization to providers' value prop
  src/Media.tsx
  src/Utils.ts
Labels: Version: Patch

#253 Add style prop to Media
  src/Media.tsx
Labels: Version: Minor

#263 chore: update dependabot reviewers
  .github/dependabot.yml
Labels: Version: Trivial
