Repository artsy/fresnel, pull requests merged in 2023-11, with the labels that each got.

#341 React 18 Support: Cleanup DOM during hydration to avoid mismatch
  examples/kitchen-sink/src/App.tsx
  examples/kitchen-sink/src/client.tsx
  examples/kitchen-sink/src/server.tsx
  examples/nextjs/src/pages/index.tsx
  examples/ssr-rendering/src/App.tsx
  package.json
  src/Media.tsx
  src/Utils.ts
Labels: Version: Major

#344 docs(readme): Update with react 18 / 17 install instructions
  README.md
Labels: Version: Trivial

#342 fix: Avoid undefined class name
  src/Media.tsx
Labels: Version: Patch

#345 fix(install): remove postinstall
  .gitignore
  .vscode/settings.json
  dist/Breakpoints.js
  dist/Breakpoints.js.map
  dist/DynamicResponsive.js
  dist/DynamicResponsive.js.map
  dist/Interactions.js
  dist/Interactions.js.map
  dist/Media.js
  dist/Media.js.map
  dist/MediaQueries.js
  dist/MediaQueries.js.map
  dist/Utils.js
  dist/Utils.js.map
  dist/__test__/Breakpoints.test.js
  dist/__test__/Breakpoints.test.js.map
  dist/__test__/Media.test.js
  dist/__test__/Media.test.js.map
  dist/__test__/Utils.test.js
  dist/__test__/Utils.test.js.map
  dist/index.js
  dist/index.js.map
  package.json
  tslint.json
Labels: Version: Patch

#346 fix(next): Make work with next via suppressHydrationWarning
  dist/Breakpoints.d.ts
  dist/DynamicResponsive.d.ts
  dist/Interactions.d.ts
  dist/Media.d.ts
  dist/Media.js
  dist/Media.js.map
  dist/MediaQueries.d.ts
  dist/Utils.d.ts
  dist/index.d.ts
  src/Media.tsx
  src/__test__/Media.test.tsx
Labels: Version: Patch
